### PR TITLE
Update jupyter notebook for pylibczirw 4.0.0 to have uri read changes

### PR DESCRIPTION
**Pull request by CraigZeiss**

### CODE REVIEW

**Comment by sebi06** [comment]
Hi @CraigZeiss,

I think it is a good idea to point to an URL that contains a usefull CZI image. I could add a "nice-looking" CZI to the place where the notebook is located?

**Comment by soyers** [comment]
I just had a quick look at the changes in the pylibczirw code and it seems like the changes should be backward compatible. The reader class is extended by an additional optional parameter. If there are no objections from @CraigZeiss's side, I propose to go for v3.6.0 instead. (-> rename the notebook in this PR and adjust the import statement inside the notebook).

**Comment by CraigZeiss** [comment]
> o point to an URL that contains a usefull CZI imag

i can add am image, but need a specific one and location to add

**Comment by CraigZeiss** [comment]
> And is there a reason why this needs a new major version 4.0.0, because I thought it is backwards compatible. Or is it not?

> I just had a quick look at the changes in the pylibczirw code and it seems like the changes should be backward compatible. The reader class is extended by an additional optional parameter. If there are no objections from @CraigZeiss's side, I propose to go for v3.6.0 instead. (-> rename the notebook in this PR and adjust the import statement inside the notebook).

for the version upgrade, while the code is backward compatible, the build now requires vcpkg and the cmake has changed so we might not support all OSs (since now we dont have mac specific cmake anymore)
after discussing this with felix, decided to change to 4.0.0

**Comment by soyers** [comment]
Ah, got it. If the build requirements changed, it's probably a good idea to increment the major verison. Thanks for clarifying :)

**Comment by CraigZeiss** [comment]
> can add am image, but need a specific one and loc

added the image you uploaded as raw link

**Review by sebi06 — APPROVED** [review]
Approved as discussed.

**Pull request merged**
